PyO3/rust-numpy

README.md
example/extensions/src/lib.rs
src/array.rs
src/convert.rs
src/lib.rs
src/types.rs
tests/array.rs

Implement IntoPyArray

---

src/array.rs
src/convert.rs
src/error.rs
src/types.rs
tests/array.rs

For my personal usage :upside_down_face:

Add `PyArray::from_vec2`

---

README.md
example/extensions/src/lib.rs
src/lib.rs

Avoid glob imports in examples

---

README.md
example/extensions/src/lib.rs

Miscellaneous minor edits to improve clarity and correct English use.

Copy edit README

---

src/array.rs
src/error.rs

To support more numpy operations

Rename ArrayCastError to ErrorKind

---

.travis.yml
Cargo.toml
README.md
appveyor.yml
build.rs
ci/travis/test.sh
examples/simple-extension/setup.py
examples/simple-extension/tests/test_ext.py
examples/simple-extension/tox.ini
src/npyffi/mod.rs

Python2 support

---

README.md
examples/simple-extension/src/lib.rs
src/array.rs

Return Py<T> in to_owned

---

.travis.yml
examples/linalg/Cargo.toml
examples/linalg/requirements-dev.txt
examples/linalg/rust_linalg/__init__.py
examples/linalg/setup.py
examples/linalg/src/lib.rs
examples/linalg/tests/test_linalg.py
examples/linalg/tox.ini

And now looking for a good benchmark problem :thinking:

Add ndarray-linalg example

---

Cargo.toml
README.md
examples/linalg/Cargo.toml
examples/linalg/src/lib.rs
examples/simple-extension/Cargo.toml
examples/simple-extension/src/lib.rs
src/array.rs
src/slice_box.rs
tests/array.rs

Hi,
first of all thanks for your work and for maintaining this crate! Unfortunately it doesn't work with the current version of PyO3. I've tried to make the necessary changes, but since I don't really know what is going on in the code, I've mainly just been randomly poking around. I managed to make it compile, but I'm having problems with the tests: 
```
Compiling pyo3 v0.6.0
Compiling numpy v0.4.1 (/home/stefan/coding/rust-numpy)
Finished dev [unoptimized + debuginfo] target(s) in 4.11s
Running target/debug/deps/numpy-46aed5f0d38cd7ee
running 3 tests
test array::test_dyn_to_owned_array ... ok
test array::test_get_unchecked ... ok
test npyffi::array::call_api ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/array-33a86790c914bbab …
```

bump to 0.6.0 (broken)

---

src/array.rs

FIx the documents of PyArray::get/get_mut

---

Cargo.toml
README.md
appveyor.yml
ci/travis/test.sh
examples/linalg/src/lib.rs
examples/simple-extension/Cargo.toml
examples/simple-extension/src/lib.rs
src/array.rs
src/convert.rs
src/error.rs
src/lib.rs
src/npyffi/array.rs
src/slice_box.rs
tests/array.rs

build: Transit package to 2018 edition

---

src/array.rs
src/convert.rs
src/error.rs
src/types.rs
tests/to_py.rs

Fix to_pyarray for not-contiguous array

---

Cargo.toml
README.md

Bump version to 0.10

---

src/error.rs
src/lib.rs
src/npyffi/flags.rs
src/npyiter.rs
tests/iter.rs

This is a highly incomplete first attempt at creating a safe wrapper for NdIter. If anyone has any feedback on code style etc. I'll happily take it as I keep working.
Continues #129

Safe NpyIter Interface.

---

CHANGELOG.md
Cargo.toml
README.md

Bump version to 0.12.1

---

.travis.yml

Fix MSRV CI

---

CHANGELOG.md
Cargo.toml
examples/linalg/Cargo.toml
examples/simple-extension/Cargo.toml
src/array.rs
src/dtype.rs
tests/array.rs

Companion to https://github.com/PyO3/pyo3/pull/1279
Probably don't merge this _at least_ until the above PR is merged into pyo3.

Update to PyO3 0.13

---

Cargo.toml

I propose to add a `rayon` feature to forward ndarray's one (in order to enable parallelism).

Add ndarray `rayon` feature

---

Cargo.toml

Bump numcomplex to the most recent version.

Feat: bump numcomplex

---

src/dtype.rs

Convert int64 to NPY_LONG if possible

---

.github/workflows/doc.yml
.gitignore
CHANGELOG.md
Cargo.toml
README.md
examples/linalg/README.md

- Change references from master branch to main
- Update some links
- Fix crates.io badge
- Various formatting/spelling changes

Fix crates.io badge and update some links

---

src/dtype.rs
src/npyffi/mod.rs
src/npyffi/objects.rs

This is a follow-up to #216
Fixes #138

Add an example on how to use custom element types

---

src/array.rs
src/npyiter.rs
src/slice_box.rs
tests/to_py.rs

Fix SliceBox-induced type confusion

---

CHANGELOG.md

cc @adamreichold - I think these changes are all since 0.15 and are user-facing, so worth noting in the CHANGELOG?

changelog: add some recent fixes

---

README.md
examples/linalg/Cargo.toml
examples/simple-extension/Cargo.toml

* As discussed, do not recommend old crate versions with known issues
* Move the examples to the front as they are what most people will look for when deciding whether to use a crate

RFC: Do some copy-editing of the README

---

CHANGELOG.md

Merges the CHANGELOG from 0.15.1 into main.

update CHANGELOG for 0.15.1 release

---

.github/workflows/ci.yml
.gitignore
README.md

(As suggested via @davidhewitt, pretty much copied from pyo3's CI config)

Add codecov to CI

---

src/convert.rs

Related to https://github.com/PyO3/rust-numpy/pull/275#discussion_r805674796

NpyStrides does not require SBO as the upper limit is statically known.

---

src/array.rs
src/dtype.rs
src/error.rs
src/lib.rs
src/slice_container.rs

4 source files done, 15 more to go... :sweat:

Do some copy-editing and start making use of intra doc links

---

.github/workflows/ci.yml
x.py

Sorry for the separate PR, just generally catching up to the development tooling for PyO3 here.

Development tooling catch-up, redux

---

src/borrow.rs
tests/borrow.rs

I was aiming for just gaming the coverage up, but the tests did actually not compile because those wrappers miss a `Debug` impl which means this does actually improve things.

Add missing implementations of the Debug trait for the borrow checking wrapper types.

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
src/dtype.rs
tests/array.rs
x.py

Add support for 16-bit floating point numbers.

---

src/array.rs
src/borrow.rs
src/convert.rs
src/error.rs
src/lib.rs
src/npyffi/mod.rs
src/npyiter.rs

Extracted out of #309 as that one will take more time and a smaller PR should be easier to review.

Consolidate deny-missing-docs and missing-debug-implementations lints.

---

.github/workflows/ci.yml

Backport of #342 to `release-0.17` branch. This will make me more sure that what I'm releasing definitely has fixes!

Add a CI job running test in release mode and under address sanitizer.

---

CHANGELOG.md
src/array.rs
src/convert.rs

Ensure that memory in dimensions is correctly treated as mutable.
@terrorfisch can you confirm this is what you meant?

fix UB in to_npy_dims

---

.github/workflows/ci.yml

* Replaced deprecated `actions-rs/toolchain` with `dtolnay/rust-toolchain`
* Updated `actions/setup-python` to v4

Add Python 3.11 to test matrix

---

Cargo.toml
src/array.rs
src/borrow/mod.rs
tests/borrow.rs

New version [was released](https://github.com/dimforge/nalgebra/blob/dev/CHANGELOG.md#0320-14-jan-2023) and the author renamed `Slice` into `View`.

Update to nalgebra 0.32

---

src/npyffi/array.rs
src/npyffi/ufunc.rs

While we do not strictly need all the capabilities and guarantees of PyO3's GILOnceCell, reducing the amount of open-coded synchronization seems like it is worth it to me. It also better centralizes GIL-based synchronization concerns in the PyO3 crate where alternative implementations better matching the Python implementation could be provided.

Drop bespoke GILOnceCell implementation used to cache capsule API

---

.github/workflows/ci.yml

- add Python 3.14 to the test matrix
- move to PyPy3.11

ci: test 3.14
