- Cargo.toml
- example/extensions/Cargo.toml
- example/extensions/src/lib.rs
- src/array.rs
- src/convert.rs
- src/error.rs
- src/lib.rs
- src/npyffi/array.rs
- src/npyffi/mod.rs
- src/npyffi/objects.rs
- src/npyffi/types.rs
- src/npyffi/ufunc.rs
- tests/array.rs
on #29 
Add global variable `PyArray_Type_Global` to adapt to pyo3 interface
> Fix build of Pyo3 branch

- Cargo.toml
- example/extensions/Cargo.toml
- example/extensions/src/lib.rs
- src/array.rs
- src/convert.rs
- src/error.rs
- src/lib.rs
- src/npyffi/array.rs
- src/npyffi/mod.rs
- src/npyffi/objects.rs
- src/npyffi/types.rs
- src/npyffi/ufunc.rs
- src/types.rs
- tests/array.rs
Resolve #23 
- It is hard to support both PyO3 and rust-cpython interface.
- rust-numpy 0.2.* uses rust-cpython, and will be deprecated after PyO3 can be compiled with stable Rust https://github.com/PyO3/pyo3/issues/5
- rust-numpy 0.3 uses PyO3
TODO
--------
> PyO3 backend

- example/.gitignore
- example/extensions/Cargo.toml
- example/extensions/src/lib.rs
- example/rust_ext/__init__.py
- example/setup.py
- example/test.py
- example/tests/test_ext.py
- src/array.rs
Suddenly now this hack
```rust
#[pymodinit(_rust_ext)]
fn init_module(py: Python, m: &PyModule) -> PyResult<()> {
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// You **must** write this sentence for PyArray type checker working correctly
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
let _np = PyArrayModule::import(py)?;
```
is necessary.
> Fix example

- Cargo.toml
- example/extensions/Cargo.toml
- example/extensions/src/lib.rs
- example/rust_ext/__init__.py
- example/setup.py
The hygiene rules changed in recent nightlies, breaking the macros, which is fixed in 0.3.1.
> Upgrade to pyo3 0.3.1

- src/array.rs
- tests/array.rs
I know it can't be bottle neck, but some rust user don't like useless allocation so I think it's better to return slice.
This PR also includes
- Modification of doc links. I think Python API link is more user friendly than C-API link
- Add doc some doc examples
> Modify PyArray::shape & PyArray::strides to return slice

- src/array.rs
- src/convert.rs
They're just a wrapper of `IntoPyArray` but since users can use these methods without importing `IntoPyArray` I think they're useful.
> Add PyArray::from_vec and PyArray::from_ndarray

- src/convert.rs
- tests/array.rs
Implement `IntoPyArray` for `[T; 1]` to `[T; 32]`
> Implement IntoPyArray for small array types

- Cargo.toml
- example/extensions/Cargo.toml
- example/extensions/src/lib.rs
- example/setup.py
- src/array.rs
- src/convert.rs
- src/error.rs
- src/lib.rs
- src/npyffi/array.rs
- src/npyffi/ufunc.rs
- src/types.rs
- tests/array.rs
Currently, this code
```rust
let v: Vec<i32> = vec![1, 2, 3];
let pyarray = PyArray::from_vec::<i64>(py, &np, v);
```
causes panic.
But, isn't it annoying to give a type annotation like `from_vec::<i64>`, and isn't it really user-friendly to cause panic?
So, this PR introduces `PyArray<T>` instead of `PyArray`.
By this change, when we write
```rust
let v: Vec<i32> = vec![1, 2, 3];
let pyarray = PyArray::<i64>::from_vec(py, &np, v);
```
, we can get compile error.
@termoshtt 
This is a breaking change so I want to hear your opnion :slightly_smiling_face:
> Static type checking with PhantomData

- Cargo.toml
- example/extensions/Cargo.toml
This fixes and the build for python3.5 for me and would also be required for publishing on pypi
> Make the example an extension module

- src/array.rs
- src/convert.rs
- src/lib.rs
- tests/array.rs
According to [rust API guideline](https://rust-lang-nursery.github.io/api-guidelines/naming.html), we should use `to_` to
- borrowed -> borrowed
- borrowed -> owned (non-Copy types)
- owned -> owned (Copy types) 
but our `to_pyarray` takes `self` for all types.
And, since objects we send to numpy API are controlled by Python GC, I think all Rust->Python conversion APIs consume lifetime, so I decided to remove `ToPyArray` trait.
Instead of this, I added `from_iter` method to `PyArray`, which takes `impl IntoIterator`.
> Remove ToPyArray and Add PyArray::from_iter

- .travis.yml
- ci/travis/deploy.sh
Since docs.rs build can often be broken for nightly
> Add master doc

- README.md
I just saw your 0.3 release announcement and noticed this in the README.
> Update ndarray repository name and URL

- README.md
- example/extensions/src/lib.rs
- src/array.rs
- src/convert.rs
- src/lib.rs
- src/npyffi/array.rs
- src/npyffi/mod.rs
- src/npyffi/ufunc.rs
- tests/array.rs
and use static variable to access Numpy C APIs.
Since nowt we can't ensure operation's safety by `PyArrayModule`'s lifetime, I changed all APIs to return or take `&'py PyArray`.
TODO:
> Remove PyArrayModule

- src/array.rs
- src/convert.rs
- src/lib.rs
So that we can use both &[2, 3] and [2, 3] to specify array dims
> Introduce ToNpyDims trait

- src/array.rs
- src/convert.rs
- tests/array.rs
We should treat only &[usize] or [usize; N] as dimension
> Remove some ToNpyDims implementation

- README.md
- example/extensions/src/lib.rs
- src/array.rs
- src/convert.rs
- src/error.rs
- src/lib.rs
- src/npyffi/array.rs
- src/types.rs
- tests/array.rs
This PR changes `PyArray<T>` into `PyArray<T, D>`, where `D` represents the dimension, like ndarray does.
In [this comment](https://github.com/rust-numpy/rust-numpy/pull/41#issuecomment-408663714) I denied this approach, but when I added `get` methods in #68, I thought this idea good, to restrict invalid index.
> Fixed dimension by PhantomData

- README.md
- example/extensions/src/lib.rs
- src/array.rs
- src/error.rs
- src/lib.rs
Implement From<ErrorKind> for PyErr and now IntoPyErr is only for
passing message to Python
> Refactor IntoPyErr

- src/array.rs
I can't compile the current code because of the following error:
```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
--> rust-numpy/src/array.rs:183:59
|
183 |     pub unsafe fn from_borrowed_ptr(py: Python, ptr: *mut pyo3::ffi::PyObject) -> &Self {
|                                                                                                         ^^^^
|
= help: add #![feature(extern_prelude)] to the crate attributes to enable
```
Tested with rustc 1.31.0-nightly (14f42a732 2018-10-14) and rustc 1.30.0-nightly (2d4e34ca8 2018-09-09).
Using ffi instead of pyo3::ffi is enough for fixing that.
(question: how does it work on Travis?)
> Fix experimental access to extern crates

- README.md
- example/extensions/src/lib.rs
- example/setup.py
- example/tests/test_ext.py
- src/array.rs
- src/convert.rs
- src/lib.rs
- src/slice_box.rs
- tests/array.rs
This PR re-implements `IntoPyArray` trait, which was removed by #68.
To prevent memory leak, I set `SliceBox`(just a thin wrapper of slice) as a base type of array.
TODO:
> Revive into_pyarray

- Cargo.toml
- examples/simple-extension/Cargo.toml
- examples/simple-extension/README.md
The python code in the `simple-extension` example readme doesn't seem to be complete.
When running it in its present form one gets an error about a module not being callable.
`rust_ext.axpy` function was probably meant to be called.
> Fix simple-extension example readme

- .travis.yml
- examples/simple-extension/rust_ext/__init__.py
- examples/simple-extension/setup.py
- examples/simple-extension/tests/test_ext.py
- examples/simple-extension/tox.ini
This lints examples/simple-extension with flake8 for PEP8 code style. Added a check in Travis CI.
Also tried to simplify a bit the `setup.py`. The main point is that to run test, it should be sufficient to run,
```
pytest tests/
```
The use of `setup.py test` is a bit outdated  (see e.g. [[1](https://blog.ionelmc.ro/2014/05/25/python-packaging/#running-the-tests)], [[2](https://tox.readthedocs.io/en/latest/example/basic.html#integration-with-setup-py-test-command)]) and I think it's simpler to just run `pytest test` directly (or use tox as it's done here).
Marking as WIP, I'm not fully sure if something else would need fixing in `tox.ini`..
> Lint examples/simple-extension and try to simplify setup.py

- src/array.rs
I also added a test. 
I'm not sure exactly how the fix works unfortunately. It seems to me that the before and after should be functionally equivalent (apart from the allocation I introduced).
> Fix panic when calling `to_owned_array` on `PyArrayDyn`

- .travis.yml
- appveyor.yml
- ci/travis/test.sh
- src/array.rs
- src/types.rs
- tests/array.rs
Pasted the test code as example
```rust
let py = gil.python();
let dict = PyDict::new(py);
let string = pyo3::types::PyString::new(py, "Hello python :)");
let a = vec![dict.as_ptr(), string.as_ptr()];
let arr = a.into_pyarray(py);
py_assert!(py, arr, "arr[0] == {}");
py_assert!(py, arr, "arr[1] == 'Hello python :)'");
```
I think it's helpful when we want to avoid `Vec -> list` overhead.
> Allow *mut ffi::PyObject as an element of PyArray

- src/types.rs
- tests/array.rs
Passing a uint64 numpy array in an x86_64 arch raised the following
exception:
Fix the following error:
E       TypeError: Extraction failed:
E        from=(dim=1, dtype=Uint64), to=(dim=_, dtype=Uint64)
E        context: [FromPyObject::extract] typecheck failed
Now it works well
> fix Uint64 type for x86_64 architectures

- .travis.yml
- Cargo.toml
- README.md
- appveyor.yml
- examples/linalg/setup.py
- examples/simple-extension/Cargo.toml
- examples/simple-extension/setup.py
- src/npyffi/mod.rs
This release drops Python2 support
> Update PyO3 to 0.7 and release 0.6

- src/types.rs
- tests/array.rs
On master, trying to convert e.g. an `Array1<usize>` to Python fails due to the conversion not being implemented for `usize` dtype.
I tried to add it following the suggestion in https://github.com/rust-ndarray/ndarray/issues/493#issuecomment-424043912
If I understand correctly, usize should map to either `np.uint32` or `np.uint64` depending on the architecture.
> Support converting Array1<usize>

- examples/linalg/Cargo.toml
- examples/linalg/setup.py
- examples/simple-extension/setup.py
Looks like this may have been left out from https://github.com/rust-numpy/rust-numpy/pull/96
Without this change I wasn't able to build the linalg example.
> MAINT Fix linalg example to use PyO3 0.7

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/linalg/Cargo.toml
- examples/linalg/setup.py
- examples/simple-extension/Cargo.toml
- examples/simple-extension/setup.py
- src/array.rs
- src/slice_box.rs
> Update pyo3 to 0.8 and bump version to 0.7

- README.md
- examples/linalg/Cargo.toml
- examples/simple-extension/Cargo.toml
- src/array.rs
- src/convert.rs
- src/npyffi/mod.rs
- src/npyffi/objects.rs
- src/npyffi/types.rs
- src/types.rs
- tests/array.rs
- tests/to_py.rs
There are some problems with reference counting and ... now I have no idea to fix it.
Maybe `to_pyarray` can be safe but anyway `TypeNum` is not appropriate for `PyObject`.
Resolves #113.
> Disable Vec<*mut ffi::PyObject> <-> numpy.ndarray conversion

- src/array.rs
- src/error.rs
- src/lib.rs
- tests/to_py.rs
They must be handled manually.
> Properly fetch errors in Python interpreter

- src/array.rs
This PR changes the way the initial capacity is calculated for `PyArray::from_iterator`.
If `size_hint` gives an upper bound, that upper bound is used as the initial capacity. Else, either the minimum bound from the size hint or the original `512 / size_of::<T>()` is used, whichever is larger.
Additionally, the PR fixes an off-by-one in the resize condition. The old check would resize the array one element too soon. That meant doubling the array size unnecessarily, even if the size hint gave a correct upper bound .
With these changes, `from_iterator` is now pretty much equally performant as `from_exact_iter`. The only remaining difference is that the loop still has to check if the capacity is exceeded, since we can't rely on the size hint for memory safety. Otherwise I would have …
> Use size_hint in PyArray::from_iter.

- .travis.yml
- README.md
- appveyor.yml
- travis
- switch to released version of 3.8
- remove 3.8 from allowed_failures
- appveyor
- add 3.8
> Update CI for python 3.8

- Cargo.toml
pyo3 master branch has updated since the rust-numpy v0.8.0 was created and adapted, making this branch incompatible. Instead of using the git path, we can use the "0.9.0-alpha.1" version on crates.io, which almost compiles. There's still a specialization problem, but that's another issue.
> Switch v0.8.0's pyo3 crate version from git repo to crates.io alpha

- Cargo.toml
- README.md
- examples/linalg/Cargo.toml
- examples/simple-extension/Cargo.toml
- src/array.rs
- src/slice_box.rs
- tests/array.rs
Needs https://github.com/PyO3/pyo3/pull/750 merged
> Update PyO3 to 0.9.0

- .gitignore
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/.gitignore
- examples/simple-extension/src/lib.rs
- src/array.rs
- src/convert.rs
- src/lib.rs
- src/npyffi/array.rs
- src/readonly.rs
- tests/array.rs
- tests/to_py.rs
Fixes #99 and #107.
This PR makes `as_slice`, `as_slice_mut`, `as_array` and `as_array_mut` unsafe and introduces `as_cell_slice` and `PyReadonlyArray`.
We can safely use `PyReadonlyArray::as_array` like:
```rust
#[pyfn(m, "axpy")]
fn axpy_py<'py>(
py: Python<'py>,
a: f64,
x: PyReadonlyArrayDyn<f64>,
y: PyReadonlyArrayDyn<f64>,
) -> &'py PyArrayDyn<f64> {
let x = x.as_array();
let y = y.as_array();
axpy(a, x, y).into_pyarray(py)
}
```
.
The trick behind this readonly array is quite simple: disabling the writeable flag when constructing, and recovering the original flag when dropping.
> Introduce PyReadOnlyArray

- CHANGELOG.md
- src/array.rs
- src/convert.rs
- src/error.rs
- src/lib.rs
- src/npyffi/array.rs
- src/readonly.rs
- src/types.rs
- tests/to_py.rs
I hope this to be the last step to 0.10.0.
`TypeNum` trait is refactored as `Element`, and ~`PyArray<PyObject>` is allowed again.~
> Refactor Element trait 

- CHANGELOG.md
- src/array.rs
- src/lib.rs
- src/npyffi/mod.rs
- src/readonly.rs
It's unsafe for the same reason as `as_slice`.
Originally pointed out by @tanriol in [the comment](https://github.com/PyO3/rust-numpy/pull/140#issuecomment-659278530), thanks!
> Introduce PyReadonlyArray::get and Make PyArray::get unsafe

- Cargo.toml
- examples/linalg/Cargo.toml
- examples/simple-extension/Cargo.toml
- src/array.rs
- src/error.rs
- src/npyffi/array.rs
- src/npyffi/ufunc.rs
I tried using the current pyo3 master branch but ran into problems.
This is the current error which I guess stems from the changes to `PyDowncastError`.
```
--> src/array.rs:134:28
|
134 |                 return Err(PyDowncastError.into());
|                            ^^^^^^^^^^^^^^^-----
|                            |
|                            help: use the path separator to refer to an item: `PyDowncastError::into`
```
> Update to pyo3 0.12.0

- src/array.rs
- tests/array.rs
A temporally fix for #151. 
This is redundant and should be replaced with a proper constructor in the future.
> Properly handle negative strides

- Cargo.toml
Specifying a `license-file` field informs crates.io that this crate is
under a non-standard license[1], and it publishes the package as
such[2]. Specifying the license with the `license` field allows
crates.io to expose the actual license information, which allows this
project to be used in certain corporations with automatic license
checking. See pyo3 as an example[3][4].
[1] https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
[2] https://crates.io/api/v1/crates/numpy/0.13.1
[3] https://crates.io/api/v1/crates/pyo3/0.13.2
[4] https://github.com/PyO3/pyo3/blob/v0.13.2/Cargo.toml#L12
> Publish with `license` field instead of `license-file`

- Cargo.toml
The `macros` feature of `pyo3` is only necessary for the tests.
This saves a bunch of unnecessary dependencies when using `rust-numpy` as a dependency.
> Don't enable pyo3/macros by default.

- .github/workflows/ci.yml
- Cargo.toml
- examples/linalg/Cargo.toml
- examples/simple-extension/Cargo.toml
Blocked on https://github.com/rust-ndarray/ndarray-linalg/pull/273
> Support ndarray 0.15

- Cargo.toml
- README.md
- examples/linalg/Cargo.toml
- examples/linalg/pyproject.toml
- examples/linalg/src/lib.rs
- examples/simple-extension/Cargo.toml
- examples/simple-extension/pyproject.toml
- examples/simple-extension/src/lib.rs
- src/array.rs
- src/dtype.rs
- src/npyiter.rs
- src/slice_box.rs
- src/sum_products.rs
This implies an API change due to re-exported types from PyO3.
> Bump PyO3 version to 0.14

- src/array.rs
- src/dtype.rs
- src/slice_box.rs
This is a follow-up to #189. I think the main benefit besides removing two unsafe usages is propagating the `Send` bound which seems to imply that `Element` must indeed be `Send` to be wrapped within `SliceBox` and managed by Python.
Taking this a bit further, there seems to be nothing slice or box specific about `SliceBox`, i.e. we could just as well have a
```rust
struct Opaque<T>(pub(crate) T);
```
which does not care about its contents at all, that is besides making it possible for Python to indirectly call `T`'s `Drop` implementation.
> Avoid raw pointers in SliceBox and make the Send bound explicit

- .github/workflows/ci.yml
- src/convert.rs
To ensure that it is used instead of the one shipped with the base image.
Fixes #198
> Install MSRV toolchain as default

- Cargo.toml
When building rust-numpy with the rust/cargo 1.48 packaged on Debian
bullseye the build fails because in Cargo 1.48 the resolver option was a
nightly only feature and Cargo errors. This feature wasn't stabilized
until 1.51. I think we aren't catching this in the MSRV jobs because
1.41 is old enough that the resolver option wasn't known.
> Remove resolver argument from Cargo.toml

- src/dtype.rs
> Mark `Element` unsafe

- src/array.rs
- src/convert.rs
- src/dtype.rs
- tests/to_py.rs
I am not sure what changed since https://github.com/PyO3/rust-numpy/pull/143#issuecomment-658867164 or whether the segmentation fault was only triggered by a more involved test but this seems to work using Python 3.8.2 on Linux. (Similarly to how https://github.com/PyO3/rust-numpy/issues/138#issuecomment-962435764 worked in this environment.)
Fixes #175
> Give PyArray<PyObject> another try.

- src/array.rs
- tests/array.rs
Luckily, NumPy will always zero-initialize object pointers, c.f. https://github.com/numpy/numpy/blob/84e0707afa587e7655410561324ac36085db2b95/numpy/core/src/multiarray/ctors.c#L826-L835, so that even without invoking `Self::zeros`, the return values of `Self::new` will always be safe to drop.
However their elements will be invalid (null pointers are not valid instances of `PyObject` as `Py<...>` is built on `NonNull<...>`). Hence the method is marked `unsafe` as referencing its elements will invoke undefined behaviour. To actually initialise the elements, the new `uget_raw` method is provided (and used internally in `from_iter`, `from_exact_iter`, `from_vec2` and `from_vec3` where we currently invoke UB ourselves).
Fixes #217
> Make the PyArray::new method unsafe and document what can and cannot be done with its return value.

- src/npyffi/array.rs
- src/npyffi/ufunc.rs
While the GIL is held when the API pointer is updated, this can still race with other threads checking the current value of the API pointer (without holding the GIL) and should therefore using atomics.
The loads and stores are performed using acquire-release semantics as we want to dereference the pointer and hence any stores to the referenced memory need to be visible to us.
The get function should also be unsafe as the offset it uses cannot be verified which might create an invalid pointer invoking undefined behaviour as per the contract of [`pointer::offset`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.offset).
Finally, the initialization code is moved into a separate cold function to improve code locality for the fast path.
I suspect that even on strongly …
> Make API globals thread safe using atomics

- README.md
It is preferred and there is no direct dependency given in the Cargo.toml.
Fixes #224
> Use re-export of ndarray in example in the README.md

- src/convert.rs
> Fix typo in IntoPyArray docs.

- CHANGELOG.md
- src/array.rs
- tests/to_py.rs
> Make arrays backed by owned data writeable.

- src/array.rs
- src/convert.rs
- tests/array.rs
> Add PyArray::borrow_from_array to expose array data with ownership being tied to anyother Python object

- .github/workflows/doc.yml
- README.md
We run it only for `main` anyway and pushing this into sub folder seems to be the underlying reason for #205. I also removed the comment from the main README which might steer people away from docs.rs which works nicely in my experience.
Fixes #205
> Simpliy the GitHub pages workflow

- .github/workflows/ci.yml
- src/array.rs
But disable needless-lifetimes lint as we often want to make the GIL lifetime explicit.
> Make Clippy stricter

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/array.rs
- src/dtype.rs
- src/lib.rs
So that we do not pull in the pre-1.0 version into other crates dependency tree.
> Bump dependency on cfg-if

- CHANGELOG.md
- Cargo.toml
- src/array.rs
- src/npyffi/array.rs
- src/npyffi/ufunc.rs
- tests/to_py.rs
Part of the discussion at https://github.com/PyO3/rust-numpy/pull/240#issuecomment-1006395111
@davidhewitt If I understood https://github.com/PyO3/rust-numpy/pull/233#issuecomment-1005247799 correctly, I should put a `v0.15.1` tag on the last commit here after review?
> Backport fixes for 0.15.1

- Cargo.toml
Bumps the version on main to match the newest released.
> bump version to 0.15.1

- CHANGELOG.md
- Cargo.toml
Since some contributors are not involved in PyO3 team (e.g., the original author @termoshtt), I employed dual authorship (rust-numpy and PyO3 developers).
Also, I updated the document link and added `categories`.
Let me know if you have any idea 😃
> Update metadata in Cargo.toml

- CHANGELOG.md
- Cargo.toml
- examples/simple-extension/src/lib.rs
- src/array.rs
- src/convert.rs
- src/dtype.rs
- src/error.rs
- src/lib.rs
- tests/array.rs
@adamreichold Here comes, as promised 😄 
This is the preliminary PR to enable further work on #254.
Although there's some breaking changes in here, it's probably better to do it all in one batch because many of these changes are inter-related. I believe all changes are improvements, in one way or another; and there's also some fixes.
An unsorted list of changes:
- Replace `Element::DATA_TYPE` with `Element::IS_POD`
- Otherwise, we would run into serious complications when trying to implement record types. Also, this is much simpler since all we need really is a quick way to check whether a type is pod or not.
- Remove `Element::same_type()`
- This was based on typenums and wouldn't work with more complex types. Now it uses `PyArray_EquivTypes`.
- Use `PyArray_NewFromDescr` instead of …
> Slim down `Element`, various dtype-related improvements and changes

- CHANGELOG.md
- src/array.rs
Fixes an instance of https://github.com/PyO3/pyo3/issues/2118 in this package.
> ExactSizeIterator is a optimization hint but unsafe code cannot trust it

- CHANGELOG.md
- src/array.rs
- tests/array.rs
The first and already discussed fix towards a resolution of #258
> Drop `as_cell_slice` and add raw array views instead

- CHANGELOG.md
- src/array.rs
- src/dtype.rs
- src/npyffi/array.rs
- src/npyffi/flags.rs
- src/npyffi/objects.rs
- src/npyffi/types.rs
- The `npyffi` stuff has been pulled out of [`pyo3-type-desc`](https://github.com/aldanor/pyo3-type-desc).
- Methods in `PyArrayDescr` mostly replicate `np.dtype` object, plus a few methods replicating C macros (this will greatly simplify writing tests in `pyo3-type-desc`, plus makes `PyArrayDescr` object somewhat useful).
> `PyArrayDescr` methods like in `np.dtype` + some missing stuff in `npyffi`

- CHANGELOG.md
- examples/simple-extension/src/lib.rs
- examples/simple-extension/tests/test_ext.py
- src/array.rs
- src/readonly.rs
- tests/array.rs
> Fix type confusion during downcastsing and add a test case showing how to extract an array from a dictionary.

- CHANGELOG.md
- src/dtype.rs
This provides the same functionality as invoking `np.dtype()` from within Python (except that passing `None` wouldn't yield float64 by default - but if we really want that for some reason, it can be changed).
> Add `PyArrayDescr::new()`

- src/array.rs
- src/dtype.rs
- src/npyffi/array.rs
- src/npyffi/mod.rs
- src/npyffi/ufunc.rs
- src/npyiter.rs
- src/sum_products.rs
Instead of slowing everything down via atomics, utilize that we already hold the GIL when accessing PY_ARRAY_API and PY_UFUNC_API.
> Protect API objects via GIL instead of atomics

- src/array.rs
Since `InvertedAxes` is basically a set of small integers, we can avoid dynamic allocations by using a word-sized bitmap in the common case of up to 32 axes.
This should also not unduly increase code slice as there is no dynamic spilling into the large representation, but the decision is rather taken once based on the dimensionality of the array.
> Small buffer optimization for InvertedAxes

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/linalg/Cargo.toml
- examples/parallel/Cargo.toml
- examples/simple/Cargo.toml
- src/array.rs
- src/dtype.rs
- src/slice_container.rs
- tests/array.rs
Update our PyO3 dependency to 0.16 and make the necessary adjustments.
> Bump PyO3 to 0.16

- CHANGELOG.md
- src/array.rs
- src/npyiter.rs
- tests/iter.rs
For the same reason that `PyArray::as_array` is unsafe, i.e. the lack of control over aliasing even for safe Rust code producing multiple iterators.
(I am not totally sure whether this is the right thing to do as I would mark them safe again in #274 after adding dynamic borrow checking but it appears slightly inconsistent as it is.)
> RFC: Mark the read-write variants of the NumPy iterators unsafe

- CHANGELOG.md
- src/array.rs
- src/lib.rs
- src/npyiter.rs
- src/readonly.rs
- tests/iter.rs
Follow-up to #279, deprecating the `npyiter` module with a short explanation of why ndarray's facilities are preferable.
> Deprecate the wrappers of the array iterator API.

- CHANGELOG.md
- Cargo.toml
- README.md
Follow-up to #259 which also bumps our version to 0.16. However, I would like to wait doing the release until after we have decided on and possibly merged the breaking changes from #279 and #280.
> Prepare to release version 0.16

- CHANGELOG.md
- Cargo.toml
- examples/parallel/Cargo.toml
- src/array.rs
- src/dtype.rs
- src/slice_container.rs
I chose to use the `pyclass` proc macro instead of trying to use features or cfgs to reduce the long-term maintenance burden as `PySliceContainer` is not special when comes to `PyClassImpl` implementors. This does mean we require PyO3's proc macros and the associated build time hit, but I suspect that the target audience using rust-numpy but not PyO3's proc macros is sufficiently limited to make this worthwhile. (I did not yet check whether there are other places in the code that could benefit from using the proc macros, but I don't expect it.)
Fixes #287
> Use the pyclass proc-macro to produce the implementation details of PySliceContainer.

- benches/array.rs
- src/array.rs
- src/convert.rs
- tests/array.rs
- tests/to_py.rs
This changes the constructors `PyArray::from_slice`, `PyArray::from_iter` and `PyArray::from_exact_iter` to first collect into Rust data structures like `Box<[T]>` or `Vec<T>` which are then wrapped into NumPy arrays.
This has upside of simplifying our code and removing multiple `unsafe` blocks. But it also has the downside that the resulting NumPy arrays do not natively manage their memory but have base objects which hold the Rust data structures.
I am not sure what this does to efficiency as the collection code for the Rust data structure will benefit from current and future optimizations for this from the standard library. On the other hand, this requires us to allocate an additional instance of our `PySliceContainer` on the Python heap managing the ownership of the data.
> RFC: Simplify constructors of one-dimensional arrays

- CHANGELOG.md
- src/npyffi/flags.rs
> Since npy_char is c_char which can be u8 or i8, we cannot unconditionally use negation.

- CHANGELOG.md
- benches/array.rs
- src/array.rs
- src/convert.rs
- src/lib.rs
- tests/array.rs
- tests/to_py.rs
Follow-up to #291. Admittedly, performance conscious code will probably try to avoid these methods, but it is relatively straight-forward to optimize them, as using pointer traversal instead of indexing brings a large improvement
```
name              main ns/iter  indexing ns/iter  diff ns/iter   diff %  speedup 
from_vec2_large   435,855       10,061                -425,794  -97.69%  x 43.32 
from_vec2_medium  6,699         507                     -6,192  -92.43%  x 13.21 
from_vec2_small   702           325                       -377  -53.70%   x 2.16 
from_vec3_large   303,579       7,109                 -296,470  -97.66%  x 42.70 
from_vec3_medium  38,732        3,000                  -35,732  -92.25%  x 12.91 
from_vec3_small   950           410                       -540  -56.84% …
```
> Benchmark and optimize PyArray2/3::from_vec2/3

- .github/workflows/ci.yml
A minimal CI job to prevent repeating #295.
Closes #295
> Add CI job to test cross building extension for Linux/AArch64.

- .github/workflows/ci.yml
- x.py
Not to be totally outdone by PyO3 which has not one but two methods to do this, adds a script to automate the most common tasks and thereby simplify things for new contributors and streamline work for the old hands.
> Add xtask Python script to automate recurring development tasks.

- CHANGELOG.md
- src/lib.rs
- src/sum_products.rs
- tests/sum_products.rs
> Extend our type signatures of inner and dot to match NumPy's types.

- CHANGELOG.md
- src/array.rs
- src/borrow.rs
- src/convert.rs
- tests/borrow.rs
- tests/to_py.rs
The thing here is making `PyArray::resize` unsafe as it may reallocate the array in-place thereby invalidate all existing pointers into its interior. The safe replacement is `PyReadwriteArray::resize` which will release and re-acquire an exclusive borrow of the array.
Does anybody now of other "destructive" methods which would need the same treatment?
I think was arguably unsound for the previous `PyReadonlyArray` as well as the following appears to work:
```rust
use numpy::{npyffi::NPY_ARRAY_WRITEABLE, PyArray};
use pyo3::Python;
Python::with_gil(|py| {
let pyarray = PyArray::arange(py, 0, 10, 1);
assert_eq!(pyarray.len(), 10);
unsafe {
(*pyarray.as_array_ptr()).flags &= !NPY_ARRAY_WRITEABLE;
pyarray.resize(100).unwrap();
}
assert_eq!(pyarray.len(), 100);
});
```
> Fixes and refinements to dynamic borrow checking

- CHANGELOG.md
- src/array.rs
- src/lib.rs
- tests/array.rs
[The docs](https://numpy.org/doc/stable/reference/c-api/types-and-structures.html#c.NPY_AO.nd) contain:
> When nd is 0, the array is sometimes called a rank-0 array. Such arrays have undefined dimensions and strides and cannot be accessed.
> Fix returning invalid strides and dimensions for rank zero arrays.

- src/array.rs
Noticed this while working on #299: While doing anything with the resulting pointer requires unsafe, producing the pointer should not. (Dereferencing `self.as_array_ptr()` should be safe for the same reasons that dereferencing it in say `PyArray::shape` is,
i.e. we ensure that `PyArray<T,D>` is only constructed for NumPy arrays.)
> Make the internal PyArray::data function safe

- src/array.rs
- src/convert.rs
- tests/array.rs
This mainly collects the code that is necessary to convert strides between NumPy's byte-unit convention and ndarray's item-unit convention which was scattered over multiple small helper types with the aim of making it easier to follow.
> Collect scattered code for converting strides

- Cargo.toml
- src/borrow.rs
- tests/borrow.rs
Follow-up to #274 as discussed in https://github.com/PyO3/rust-numpy/pull/274#issuecomment-1071048638. Should show that this can work, but still needs needs many unit tests to drive the range data structures into various stages...
> Refine dynamic borrow checking to track data ranges.

- Cargo.toml
- benches/borrow.rs
- src/borrow.rs
This does bring a measurable performance improvement for borrow operations
```
name                      std ns/iter  ahash ns/iter  diff ns/iter   diff %  speedup 
additional_shared_borrow  208          140                     -68  -32.69%   x 1.49 
exclusive_borrow          233          186                     -47  -20.17%   x 1.25 
initial_shared_borrow     289          211                     -78  -26.99%   x 1.37 
```
by adding a relatively small dependency on the `ahash` crate.
> Use AHash for borrow checking hash tables.

- src/borrow.rs
- src/lib.rs
* Further de-bloats it by removing unnecessary generics. (Not sure why I did not think of this in the earlier PR.)
* Fixes a drop bug in `PyReadwriteArray::resize` which would "double-release" the borrow if the resize operation fails.
* Optimizes releasing and cloning borrows by stashing the base address and data key in the structures.
* Fixes missing re-export of `BorrowError`.
> Further fixes and optimizations for the borrow module

- CHANGELOG.md
- benches/array.rs
- src/error.rs
- src/lib.rs
This should be especially useful for functions that accept several element types like what was discussed in #289. Even more so, as `rust-numpy` implements `PyTypeInfo::is_type_of` in terms of `FromPyObject::extract`.
The benchmark results seem to justify the manual implementation of `PyErrArguments`: 
```
name             main ns/iter  pr ns/iter  diff ns/iter   diff %   speedup 
extract_failure  13,326        90               -13,236  -99.32%  x 148.07 
extract_success  20            19                    -1   -5.00%    x 1.05 
```
> Delay formatting type errors to improve performance of failed extractions.

- CHANGELOG.md
- examples/simple/src/lib.rs
- examples/simple/tests/test_ext.py
- src/datetime.rs
- src/dtype.rs
- src/lib.rs
- x.py
It basically works, but there are still quite a few things left to do:
Closes #142
> Add support for datetime64 and timedelta64 element types

- .github/workflows/ci.yml
- Cargo.toml
- examples/linalg/Cargo.toml
- examples/parallel/Cargo.toml
- examples/simple/Cargo.toml
- x.py
As features are unified over the whole of a workspace, having the examples inside the main workspace prevents independent tests of different combinations of PyO3 features. Therefore, this PR breaks them out into separate workspaces and adjust the xtask script to still include them where appropriate.
> Break examples out of main workspace

- src/array.rs
- src/convert.rs
- x.py
No major changes but multiple fixes to the wording, but also the contents (e.g. mixed up safety properties or incorrect links) of the documentation. Small improvement to the `FromPyObject` implementation (checking dimensionality before element type because that is faster). Made `PyArray::data` public as it seem strange to expose `PyArray::as_array_ptr` but not that one.
> Copy-edit the array module.

- benches/array.rs
- src/array.rs
- src/dtype.rs
- src/error.rs
This does give us the best of both worlds, i.e. avoid having to create a `PyErr` for downcast but still keeping a single implementation for the `extract` logic. I am just not sure whether this is wort the additional effort, i.e. the extra `ExtractionError` enum.
> Avoid the overhead of creating a PyErr for downcasting.

- examples/simple/src/lib.rs
- examples/simple/tests/test_ext.py
We had at least two issues about this IIRC and I think it is not obvious how to do this. The proposed approach is safe by relying on enums and deriving `FromPyObject`, but it is certainly verbose.
(The "simple" example is also starting to be not-so-simple any more. Maybe it is time to move parts of it into separate example crates? Then again, the overhead of a crate to demonstrate a single function seems questionable.)
> RFC: Extend simple exmaple to include a function with limited polymorphism based on enums and FromPyObject.

- CHANGELOG.md
- Cargo.toml
- src/array.rs
- tests/array.rs
> Fix use-after-free when calling to_npy_dims helper method.

- .github/workflows/ci.yml
This avoids the need for instrumentation (e.g. `-Zbuild-std`) and extends coverage to doctests.
It is somewhat slower, but I think that is a reasonable price to pay for the increased coverage and simpler usage.
> RFC: Use Valgrind instead of AddressSanitizer

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/array.rs
- src/borrow.rs
- src/convert.rs
- src/lib.rs
- tests/borrow.rs
- tests/to_py.rs
This is loosely based on https://github.com/qsib-cbie/nalgebra-numpy (which is based on https://github.com/fusion-engineering/nalgebra-numpy targetting an older version of `pyo3`) but I tried to achieve a deeper integration into our existing types and optimized the `ToPyArray` implementation to copy contiguous data using `ptr::copy_nonoverlapping`.
Closes #263
> Optional support for nalgebra types

- Cargo.toml
- x.py
`half` is part of our API and hence this is a breaking change. This also increases MSRV to 1.58 if `half` is enabled. (It was already 1.51 if `half` is enabled before, i.e. not compatible with our MSRV of 1.48.)
> Bump half dependency to the current stable version

- Cargo.toml
- src/borrow.rs
- src/datetime.rs
This is motivated by the issue unearthed in #352. (The first commit fixes a luckily inconsequential mistake that slipped through review.)
In the `datetime` module, we hash a set of keys known at compile time and hence are not subject to DoS issues.
In the `borrow` module, the keys include pointer addresses which means that even if a program exposes its usage of NumPy arrays to remote user control, a DoS attack would also need detailed control over the placement of memory allocations in which case outright memory exhaustion seems to be a simpler avenue of attack.
> RFC: Replace AHash (DoS-resistant) by FxHash (simpler dependency)

- CHANGELOG.md
- src/borrow/mod.rs
- src/borrow/shared.rs
This places the global state required for dynamic borrow checking of NumPy arrays into a capsule exposed as the numpy.core.multiarray._BORROW_CHECKING_API attribute.
This has two benefits: First, all extensions built using rust-numpy will share this global state and hence cooperate in borrow checking. Second, in the future,
other libraries that want to borrow check their access to NumPy array can cooperate using this C-compatible API.
This does not checking the borrow checking implementation at all, but instead of accessing Rust static data, all accesses are funneled through the above-mentioned capsule API with access to it being cached for performance reasons as we already do for the _ARRAY_API and _UFUNC_API capsules.
This means that eventually, the implementation of the borrow checking …
> RFC: Perform borrow checking through a capsule-based API

- src/slice_container.rs
Or rather any access at all.
@davidhewitt @mejrs I think we forgot this when switching from an open-coded `#[pyclass]` to using PyO3's macros to handle the complications implies by the `multiple-pymethods` feature. Maybe yet another data point that frozen-by-default would be a good thing (if the diagnostic of how to gain `&mut self` are good enough).
> Freeze the slice container pyclass as it does not need mutable access

- src/borrow/shared.rs
- src/npyffi/array.rs
- src/npyffi/mod.rs
- src/npyffi/ufunc.rs
While this started as a simple PyO3 API usage modernization, I think we actually need to make sure the capsules stay alive as long as we hold onto pointers into their interior as the modules and hence attributes could theoretically be deleted leaving us with a dangling pointer.
Leaking references to the capsules themselves seemed like the easiest way to avoid the overhead of calling `PyCapsule_Pointer` for each access. This should not be a functional limitation as we never update the cached pointer in any case, i.e. storing `Py<PyCapsule>` would have effectively the same result as the intentional leak.
> Make sure capsules stay alive when caching pointers into their interior

- .github/workflows/ci.yml
Standing on the shoulders of giants, c.f. https://github.com/PyO3/pyo3/pull/3097
> Switch coverage format for Codecov uploads to the native one.

- src/datetime.rs
- src/slice_container.rs
We can merge this now as GILProtected was released as part of PyO3 0.18.3.
> Use GILProtected to make it explicit where we depend on the GIL for synchronization.

- src/array.rs
> Correct Typo for array.dims()

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/borrow/shared.rs
- src/datetime.rs
- src/lib.rs
- src/npyffi/mod.rs
- src/strings.rs
- tests/array.rs
This supports Unicode arrays whose element length is know at compile time.
Closes #141
> Add support for arrays of ASCII and Unicode strings

- .github/workflows/ci.yml
- CHANGELOG.md
- src/dtype.rs
- tests/array.rs
> Add minimal support for BFloat16 dtype.

- src/borrow/mod.rs
Using `#[repr(C)]` was necessary when it had multiple fields so that the `Deref` implementation from `PyReadwriteArray` to `PyReadonlyArray` is sound.
> Use a transparent repr for PyReadonly/ReadwriteArray as this has become as single field struct.

- examples/linalg/src/lib.rs
- examples/parallel/src/lib.rs
- examples/simple/src/lib.rs
- tests/to_py.rs
It seems like none of these annotations are necessary. After removing them, everything still compiles and works as expected.
> Remove unneeded lifetime annotations

- codecov.yml
Since we copied the configuration, we need to copy the fix from https://github.com/PyO3/pyo3/pull/3455
> Fix ignore pattern used to determine test coverage.

- CHANGELOG.md
- src/array_like.rs
- src/lib.rs
- tests/array_like.rs
Extracts a read only reference if the correct numpy array type is given. Tries to convert the input into the correct type otherwise.
Resolves #382
This implementation seems to work as intended and covers my personal use case. However, I am not sure how well it performs (you certainly want it to be not significantly slower than calling `np.asarray(...)` on Python side, and then extracting `PyReadonlyArray<...>` on Rust side). Also, there are several tasks remaining like documentation and proper error handling.
Do you want to take over at this point for finalizing the branch in your own style?
> PyArrayLike type introduced

- src/dtype.rs
> Add documentation on the consequences of NumPy matching C's integeer hierarchy.

- Cargo.toml
- examples/linalg/Cargo.toml
- examples/parallel/Cargo.toml
- examples/simple/Cargo.toml
- src/array.rs
- src/array_like.rs
- src/borrow/shared.rs
- src/dtype.rs
- src/npyffi/array.rs
- src/npyffi/mod.rs
- src/npyffi/ufunc.rs
- src/strings.rs
- src/sum_products.rs
- src/untyped_array.rs
- tests/to_py.rs
`pyo3` 0.21 is on the final stretch to release, with an initial beta expected in the next few days.
This starts the migration to `pyo3`s new `Bound` API. This initial PR bumps the `pyo3` version, enables the `gil-refs` feature (to suppress most of the deprecation warnings) and adjust the rest to compile and pass the tests again. 
Note:
`PyTypeInfo` needs to be updated to `is_type_of_bound` now, because otherwise `pyo3`s internals will not use the custom implementation, as found in https://github.com/PyO3/pyo3/issues/3929
I've prepared followups migrating different parts of the API in (hopefully) reviewable chunks. Generally I took a similar approach to `pyo3` itself, leaving old API around (for easy migrations) and adding deprecation warnings where necessary.
I'll leave this as a draft …
> migration to pyo3 0.21 new `Bound` API

- src/array.rs
- src/lib.rs
- src/untyped_array.rs
Following #410 
This migrates `PyUntypedArray` to the `Bound` API. This introduces `PyUntypedArrayMethods` to implement the methods on `Bound<PyUntypedArray>`. Additionally this also implements the trait on `Bound<PyArray<T, D>>`, via `as_untyped`, because we will not be able to provide a `Deref` implementation anymore, due to orphan rules and the deref to `Bound<PyAny>`. This seemed like the most reasonably option to keep the same ergonomics.
> convert `PyUntypedArray` to `Bound` API

- src/array.rs
- src/array_like.rs
- src/datetime.rs
- src/dtype.rs
- src/error.rs
- src/lib.rs
- src/strings.rs
- src/untyped_array.rs
- tests/array.rs
Following #411 
This migrates `PyArrayDescr` to the Bound API. This introduces `PyArrayDescrMethods` to implement the methods on Bound<PyArrayDescr>.
> convert `PyArrayDescr` to `Bound` API

- src/array.rs
- src/array_like.rs
- src/borrow/mod.rs
- tests/array.rs
- tests/borrow.rs
Following #412
This migrates `PyArray` to the Bound API. This introduces `PyArrayMethods` to implement the methods on Bound. The diff is a bit bigger for this one, but most of the code just moved around a bit, so I hope it's still fine.
> convert `PyArray` to `Bound` API

- src/array.rs
- src/borrow/mod.rs
- src/untyped_array.rs
- tests/borrow.rs
> Extend the documentation of the nalgebra integration to discuss its likely surprising memory layout requirements.

- src/array.rs
- src/borrow/mod.rs
- src/borrow/shared.rs
- src/convert.rs
- src/datetime.rs
- src/lib.rs
- src/untyped_array.rs
- tests/array.rs
- tests/borrow.rs
Following #415 
This migrates `PyArray` constructors to the `Bound` API. I created a commit for each constructor migration. To keep the diff reviewable I will split this over multiple PRs. This starts the migration with `PyArray::{new, borrow_from_array, from_owned_array, zeros}`.
(This also reexports `PyArray0Methods`, which we forgot in #415)
> migrate `PyArray` contructors to `Bound` API (Part 1)

- Cargo.toml
- README.md
- benches/array.rs
- examples/linalg/Cargo.toml
- examples/linalg/src/lib.rs
- examples/parallel/Cargo.toml
- examples/parallel/src/lib.rs
- examples/simple/Cargo.toml
- examples/simple/src/lib.rs
- src/array.rs
- src/array_like.rs
- src/borrow/shared.rs
- src/convert.rs
- src/lib.rs
- src/strings.rs
- src/untyped_array.rs
- tests/array.rs
- tests/to_py.rs
Following #418 
This finalizes the migration of `PyArray` constructors to the `Bound` API. This migrates with `PyArray::{from_iter, from_array, from_vec}`, alongside with `IntoPyArray` and `ToPyArrray` which they use under the hood. I think with this all constructors should be migrated.
> migrate `PyArray` contructors to `Bound` API (Part 3) 

- src/lib.rs
- src/sum_products.rs
- tests/sum_products.rs
This migrates `inner`, `dot` and `einsum` to the `Bound` API.
> deprecate `inner`, `dot` and `einsum`

- src/lib.rs
- src/sum_products.rs
- tests/array.rs
- tests/borrow.rs
- tests/sum_products.rs
This migrates the `pyarray!` macro and is the final piece of the migration to the `Bound` API of pyo3 0.21 🎉
> deprecate `pyarray!`

- CHANGELOG.md
- src/array.rs
- tests/array.rs
> Add `permute` and `transpose` methods for changing the order of axes of a `PyArray`

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/linalg/Cargo.toml
- examples/parallel/Cargo.toml
- examples/simple/Cargo.toml
- examples/simple/src/lib.rs
- src/array.rs
- src/borrow/mod.rs
- src/convert.rs
- src/datetime.rs
- src/dtype.rs
- src/lib.rs
- src/strings.rs
- src/sum_products.rs
- src/untyped_array.rs
- tests/array.rs
This PR builds on #431 to migrate to PyO3 0.22.0 without needing to activate the problematic `py-clone` feature.
PyO3 recently released version 0.22.0 which includes [many new features](https://pyo3.rs/v0.22.0/changelog), but also includes the next step in deprecating the _gil-refs_ API by putting it behind the opt-in `gil-refs` feature flag. @bschoenmaeckers's PR went long way towards updating `numpy` for the migration by mirroring the gil-refs deprecation and feature-gating the methods that depend on it, but @juntyr raised valid concerns about its unconditional activation of  PyO3's `py-clone` feature flag.
The PyO3 0.22.0 release includes [PyO3#4095](https://github.com/PyO3/pyo3/pull/4095)'s removal of the ability to clone `Py<T>` while the GIL is not held, which was implemented by …
> Update pyo3 to 0.22.0 (without "py-clone")

- .github/workflows/ci.yml
Ubuntu 24.04 no longer allows installing packages into the system environment.
> ci: updates for ubuntu 24.04

- .github/workflows/ci.yml
Adds 3.13 to the 2 matrix tests in CI. Hasn't broken anything locally but we'll see.
Closes #459 
_Side note: I'm also working on the god awful chore of raising code coverage as a slightly more significant contribution._
> add python 3.13 to ci matrix

- src/array.rs
- src/npyffi/array.rs
- src/npyffi/ufunc.rs
Local tests pass
Mentioned on #453 
Closes #454
> changed core module call to _core

- src/array.rs
- src/borrow/mod.rs
- tests/borrow.rs
The `PyReadwriteArray` understands the flag during the dynamic borrow checking, this just adds a way to set it on an array as well.  This is a safe subset of what can be achieved unsafely by mutating the `flags` field on some `*mut PyArray`.
The discussion in #456 suggested having the method return a `PyReadonlyArray`.  I feel like I might be missing something _very_ obvious here, but I couldn't spot an existing way to consume an exclusive reference into a shared one.  I added a `From` impl and then used that for now, but happy to switch it to a better version if one already exists, or drop it if we decide we don't want users to always pay the cost of re-acquiring the shared borrow (maybe there's some `mem::forget` shenanigans in conjunction with an extra "switch in place" operation that …
> Add method to clear `WRITEABLE` flag from `PyArray`

- CHANGELOG.md
- Cargo.toml
This releases the improvements by @jakelishman; notably the fixes to 32-bit windows but also the `PyReadWriteArray::make_nonwriteable` method.
I will put this live tonight unless I hear a reason to delay.
> release: 0.22.1

- Cargo.toml
This allows other crates which use slightly different versions of nalgebra to avoid type-conflicts. I tested versions `0.30` to `0.33`. The test-suite passes for all of them.
> allow versions =>0.30 <0.34 for `nalgebra`

- src/dtype.rs
- src/slice_container.rs
Prepares for the `pyo3` upgrade to 0.23 in #457.
This contains two changes:
- This implements `Sync` for `PySliceContainer` which is used as the underlying backing object for Rust allocated `numpy` arrays.
Since `PySliceContainer` "virtually" does hold elements of type `T` (which is cast away due to the no-generics limitation), construction is only allowed from `T`s that are `Sync` themselves. (Ideally we would have `unsafe impl<T: Sync> Sync for PySliceContainer<T> {}`).
- I _think_ it will hand out references into that buffer in place, so we need to require all `Element`s to be `Sync` as well. In any case I think this could only be too strong, which would not be unsound.
> make `PySliceContainer` implement `Sync`

- .github/workflows/ci.yml
- CHANGELOG.md
Upstream PyO3 does not support PyPy 3.7 and 3.8 anymore since 0.23 (PyO3/pyo3#4582). Testing against PyPy 3.9 and 3.10 now. Also there are `numpy` wheels for PyPy on Windows-x64 and MacOS now, so I included it in CI.
> drop support for PyPy 3.7 and 3.8

- Cargo.toml
It [seems like](https://github.com/rust-lang/rustc-hash/blob/master/CHANGELOG.md) `rustc-hash`'s version 1.2 is yanked, which means this crate is stuck on 1.1.
I don't think there is any harm in updating version 2.0, should hopefully give a small speedup.
> Update rustc-hash to 2.0

- CHANGELOG.md
- Cargo.toml
I think we're ready to ship the 0.23 release.
Free-threading support looks non-trivial; without the changes in #471 it won't even build so we are safe to release and fixup later, I believe.
If I hear no concerns will put this live on either Thursday or Friday.
> release: 0.23.0

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- benches/array.rs
- build.rs
- src/borrow/shared.rs
- src/datetime.rs
- src/lib.rs
- src/npyffi/mod.rs
- src/strings.rs
First pass at adding CI and tests for freethreaded Python.
Locally I get some test failures, so I will have to investigate further before this is ready even if CI is green. cc @ngoldbaum 
```
failures:
---- borrow::shared::tests::borrow_multiple_views stdout ----
thread 'borrow::shared::tests::borrow_multiple_views' panicked at src/borrow/shared.rs:836:17:
assertion `left == right` failed
left: 3
right: 1
---- borrow::shared::tests::borrow_multiple_arrays stdout ----
thread 'borrow::shared::tests::borrow_multiple_arrays' panicked at src/borrow/shared.rs:786:17:
assertion `left == right` failed
left: 2
right: 1
failures:
borrow::shared::tests::borrow_multiple_arrays
borrow::shared::tests::borrow_multiple_views
test result: FAILED. 27 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; …
```
> support 3.13t free-threaded python

- CHANGELOG.md
- Cargo.toml
Time to ship!
Will probably merge #482 first.
> release: 0.24.0

- .github/workflows/release.yml
So that it's quicker for us to publish new releases (just publish the GitHub tag).
> add release job to CI

- Cargo.toml
- src/untyped_array.rs
- x.py
Fixes the CI lint warning with 1.87. Also elides a bunch of needless named lifetimes at the same time.
> fix lint warning with Rust 1.87

- CHANGELOG.md
- Cargo.toml
- README.md
- benches/array.rs
- benches/borrow.rs
- examples/linalg/Cargo.lock
- examples/linalg/Cargo.toml
- examples/parallel/Cargo.toml
- examples/simple/Cargo.toml
- examples/simple/src/lib.rs
- src/array.rs
- src/array_like.rs
- src/borrow/mod.rs
- src/borrow/shared.rs
- src/convert.rs
- src/datetime.rs
- src/dtype.rs
- src/error.rs
- src/lib.rs
- src/npyffi/array.rs
- src/npyffi/mod.rs
- src/npyffi/ufunc.rs
- src/strings.rs
- src/sum_products.rs
- src/untyped_array.rs
- tests/array.rs
- tests/array_like.rs
- tests/borrow.rs
- tests/sum_products.rs
- tests/to_py.rs
Upgrades to PyO3 0.26
- rename `with_gil`/`allow_threads` -> `attach`/`detach`
- use `cast` instead of `downcast`
- replace `PyObject` by `Py<PyAny>`
- replace `GILOnceCell` by `PyOnceLock`
- introduce `PyArrayMethods::cast_array` and deprecate `PyArrayMethods::cast` because it clashes now with `Bound::cast`
> Upgrade to PyO3 0.26

- .github/workflows/release.yml
Adapted from pyo3/pyo3#5353 and followups
cc @davidhewitt Did you set this up for `rust-numpy` as well?
> ci: configure trusted publishing
